server:
  # 运行端口号
  port: 8103
spring:
  application:
    # 服务名称
    name: eureka-client
eureka:
  client:
    # 注册到Eureka注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    serviceUrl:
      # 配置注册中心地址
      defaultZone: http://yancy0109:123456@localhost:8004/eureka/


